/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Servidor;

import com.mycompany.proyecto2.Mapa.Mapa;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Tamara
 */
public class PantallaServidorInicializador extends javax.swing.JFrame {

    // Un mapa que se va a inicializar en esta pantalla y se pasara a la pantalla del servidor
    Mapa mapa;
    // La imagen del fondo del programa 
    ImagenFondo fondo = new ImagenFondo();
    /**
     * Creates new form PantallaServidorInicializador
     */
    // CONSTRUCTOR 
    public PantallaServidorInicializador() {
        this.setContentPane(fondo);
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciar = new javax.swing.JButton();
        lblCeldasMercado = new javax.swing.JLabel();
        txfCeldasAmenaza = new javax.swing.JTextField();
        lblCeldasAmenaza = new javax.swing.JLabel();
        txfCeldasTesoro = new javax.swing.JTextField();
        lblCeldasTesoro = new javax.swing.JLabel();
        txfCeldasVacias = new javax.swing.JTextField();
        lblCeldasVacias = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txfCantidadJugadores = new javax.swing.JTextField();
        lblCantidadCeldasServer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIniciar.setBackground(new java.awt.Color(46, 77, 71));
        btnIniciar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        lblCeldasMercado.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblCeldasMercado.setForeground(new java.awt.Color(255, 255, 255));
        lblCeldasMercado.setText("La cantidad de celdas sobrantes seran para el mercado");

        txfCeldasAmenaza.setBackground(new java.awt.Color(103, 147, 128));
        txfCeldasAmenaza.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        txfCeldasAmenaza.setForeground(new java.awt.Color(255, 255, 255));
        txfCeldasAmenaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCeldasAmenazaActionPerformed(evt);
            }
        });

        lblCeldasAmenaza.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblCeldasAmenaza.setForeground(new java.awt.Color(16, 24, 23));
        lblCeldasAmenaza.setText("Digite la cantidad de celdas con amenaza del mapa:");

        txfCeldasTesoro.setBackground(new java.awt.Color(103, 147, 128));
        txfCeldasTesoro.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        txfCeldasTesoro.setForeground(new java.awt.Color(255, 255, 255));
        txfCeldasTesoro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCeldasTesoroActionPerformed(evt);
            }
        });

        lblCeldasTesoro.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblCeldasTesoro.setForeground(new java.awt.Color(16, 24, 23));
        lblCeldasTesoro.setText("Digite la cantidad de celdas con tesoro del mapa:");

        txfCeldasVacias.setBackground(new java.awt.Color(103, 147, 128));
        txfCeldasVacias.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        txfCeldasVacias.setForeground(new java.awt.Color(255, 255, 255));
        txfCeldasVacias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCeldasVaciasActionPerformed(evt);
            }
        });

        lblCeldasVacias.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblCeldasVacias.setForeground(new java.awt.Color(16, 24, 23));
        lblCeldasVacias.setText("Digite la cantidad de celdas vacias del mapa:");

        lblTitulo.setFont(new java.awt.Font("Goudy Stout", 0, 26)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(32, 57, 53));
        lblTitulo.setText("Iniciando Servidor");

        txfCantidadJugadores.setBackground(new java.awt.Color(103, 147, 128));
        txfCantidadJugadores.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        txfCantidadJugadores.setForeground(new java.awt.Color(255, 255, 255));
        txfCantidadJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCantidadJugadoresActionPerformed(evt);
            }
        });

        lblCantidadCeldasServer.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblCantidadCeldasServer.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidadCeldasServer.setText("Digite la cantidad de jugadores que poseera este server:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(txfCeldasTesoro, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(txfCeldasAmenaza, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(txfCeldasVacias, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblCeldasVacias))
                            .addComponent(lblCeldasTesoro)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(lblCeldasAmenaza))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantidadCeldasServer)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(txfCantidadJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCeldasMercado))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addGap(38, 38, 38)
                .addComponent(lblCeldasVacias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfCeldasVacias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(lblCeldasTesoro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfCeldasTesoro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(lblCeldasAmenaza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfCeldasAmenaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblCantidadCeldasServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfCantidadJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lblCeldasMercado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        
        // Toma valores de tipo double que significan las celdas que tendra cada que
        double CeldasVacias;
        double CeldasTesoro;
        double CeldasAmenazas;
        int CantidadJugadores;
        double Total;
        
        // Un try por si hay un error en la conversion o si el rango del total no es correcto
        try {
            // Se inician los valores de las celdas con lo que se encuentra en el text field
            CeldasVacias = (Double.parseDouble(txfCeldasVacias.getText()) / 100);
            CeldasTesoro = (Double.parseDouble(txfCeldasTesoro.getText()) / 100);
            CeldasAmenazas = (Double.parseDouble(txfCeldasAmenaza.getText()) / 100);
            
            // Se busca la cantidad de jugadores
            CantidadJugadores = (Integer.parseInt(txfCantidadJugadores.getText()));
            
            // El total es la suma de los porcentajes de todas las celdas
            Total = CeldasVacias + CeldasTesoro + CeldasAmenazas;

            // Si el total es mayor a 1  o menor a 0.8 arroja una excepcion de tipo IllegalArgumentException
            if(Total > 1 || Total < 0.80){
                throw new IllegalArgumentException("Total mayor a 1 o la cantidad de celdas mercado es mayor al 20%");
            }
            
            else if(CantidadJugadores <= 1 || CantidadJugadores > 4){
                throw new IllegalArgumentException("Jugadores insuficientes");
            }
            
            // Si al final si es valido el total, inicializa el servidor
            else{
                // Crea el mapa y se lo pasa a la pantalla del servidor
                mapa = new Mapa(CeldasVacias, CeldasTesoro, CeldasAmenazas, 15, 15);
                PantallaServidor1 pantalla = new PantallaServidor1(mapa, CantidadJugadores);
                pantalla.setVisible(true);
                this.dispose(); // Cierra esta ventana para abrir la del servidor
            }

        // Los catch respectivos para las excepciones
        } catch (NumberFormatException e) {
            txfCeldasVacias.setText("");
            txfCeldasTesoro.setText("");
            txfCeldasAmenaza.setText("");
            txfCantidadJugadores.setText("");
            JOptionPane.showMessageDialog(null, "Debe de ingresar un numero valido", "Error", JOptionPane.ERROR_MESSAGE);
        } catch(IllegalArgumentException e){
            txfCeldasVacias.setText("");
            txfCeldasTesoro.setText("");
            txfCeldasAmenaza.setText("");
            txfCantidadJugadores.setText("");
            
            // Si la cantidad de jugadores es insuficiente
            if(e.getMessage().equals("Jugadores insuficientes")){
                JOptionPane.showMessageDialog(null, "Debe de ingresar un valor valido para la cantidad de jugadores", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(null, "Debe de ingresar un valor en el que la cantidad de mercado sea de un maximo del 20%", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void txfCeldasAmenazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCeldasAmenazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCeldasAmenazaActionPerformed

    private void txfCeldasTesoroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCeldasTesoroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCeldasTesoroActionPerformed

    private void txfCeldasVaciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCeldasVaciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCeldasVaciasActionPerformed

    private void txfCantidadJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCantidadJugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCantidadJugadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaServidorInicializador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaServidorInicializador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaServidorInicializador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaServidorInicializador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaServidorInicializador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel lblCantidadCeldasServer;
    private javax.swing.JLabel lblCeldasAmenaza;
    private javax.swing.JLabel lblCeldasMercado;
    private javax.swing.JLabel lblCeldasTesoro;
    private javax.swing.JLabel lblCeldasVacias;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txfCantidadJugadores;
    private javax.swing.JTextField txfCeldasAmenaza;
    private javax.swing.JTextField txfCeldasTesoro;
    private javax.swing.JTextField txfCeldasVacias;
    // End of variables declaration//GEN-END:variables

    // Clase de la imagen del fondo, esto es para que el fondo se adapte al tamano que se ponga de la pantalla
    class ImagenFondo extends JPanel{
    
        //Atributos
        private Image imagen;

        //Metodos
        public void paint (Graphics g) {
            imagen = new ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\Imagenes\\FondoInicio.png").getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight() ,rootPane);
            setOpaque(false);
            super.paint(g);
        }
    }
}
